db:
  pg_db_url: "postgres://postgres:hetu@0.0.0.0:5432"
  pg_db_name: "operator_db"
  max_connect_pool: 30
  min_connect_pool: 10
  connect_timeout: 30
  acquire_timeout: 60
queue:
  # "13.215.49.139:3000"
  queue_url: "redis://:@127.0.0.1:6379/"
  topic: "task"
net:
  rest_url: "0.0.0.0:21001"
  outer_url: "http://127.0.0.1:8080"
  dispatcher_url: "127.0.0.1:8081"
  callback_url: "http://127.0.0.1:21001/api/opml_callback"
  tee_llm_cid: 15
  tee_llm_port: 5005
node:
  node_id: "0x02a5592a6de1568f6efdc536da3ef887f98414cb"
  signer_key: "77f4b2fbf3f32687f03d84d323bd5cb443f53b0fc338b51c24e319a520c87217"
  vrf_key: "77f4b2fbf3f32687f03d84d323bd5cb443f53b0fc338b51c24e319a520c87217"
  dispatcher_address: "0x1DdBd306eFFbb5FF29E41398A6a1198Ee6Fb51ce"
  node_type: "opml"
  cache_msg_maximum: 500
  heartbeat_interval: 10
  ai_models:
    - "llama-2-7b-chat.Q4_0.gguf"
chain:
  chain_rpc_url: "https://ethereum-holesky-rpc.publicnode.com"
  vrf_range_contract: "0x27e4384ecc11810c2F49914390052b22c4e3CcC0"
  vrf_sort_precision: 6
api:
  read_maximum: 20
